services:
  
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=widget-server
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - widget
      - db
  
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    container_name: widget-server
    ports:
      - 3000:3333
    environment:
      - CLOUDFLARE_ACCESS_KEY_ID=9c61d3042114f2e4cb2a63a5a50eebef
      - CLOUDFLARE_SECRET_ACCESS_KEY=4053d29402517aa238287f20a9fc770b184ef1b0c0abc5c0403507cb05aa2984
      - CLOUDFLARE_BUCKET=ftr-upload-widget
      - CLOUDFLARE_ACCOUNT_ID=34c87ab1613a1afc6567344b2e5c1088
      - CLOUDFLARE_PUBLIC_URL=https://pub-97abb5beafd144d8b12b9244ef8767ff.r2.dev
    networks:
      - widget
  
  volumes:
    db:
  
  networks:
    widget:
      driver: bridge
    db:
      driver: bridge
      