
name: widget-server pipe

on:
    push:
        branches: [main]

jobs:
    build:
        name: build
        
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2  
            
            - name: Login to DockerHub
              id: login-dokcer-hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Generate tag
              id: generate_tag
              run: |
                SHA=$(echo $GITHUB_SHA | cut -c1-7)
                echo "sha=${SHA}" >> $GITHUB_OUTPUT
            
            - name: Build and push the image do Docker
              id: build-push-image
              env:
                DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
                IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
              run: |
                docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
                docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG


        